# Generated by Django 3.1.3 on 2022-04-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card_FA_value',
            new_name='FA_value',
        ),
        migrations.AlterField(
            model_name='face_attribute',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
